stages:
    - build
    - test
    - sonar

build:
    stage: build
    script: "mvn clean test -B"

test:
    stage: test
    script: "mvn verify -B"

sonar:
    stage: sonar
    script: "mvn sonar:sonar -B -Dsonar.host.url=https://sonarqube.johnnei.org"
